version: '3.9'

services:
  hackathon_project:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    container_name: backend
    volumes:
      - .:/usr/src/app/
    environment:
      - DB_HOST=postgres
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - SERVER_PORT
      - SERVER_IP
      - DJANGO_SECRET_KEY
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_PORT: ${DB_PORT}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  db_data:
