# Generated by Django 5.0.2 on 2024-03-02 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grades",
            name="value",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(200)]
            ),
        ),
    ]
