# Generated by Django 5.0.2 on 2024-03-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="education.group",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("STUDENT", "Student"), ("TEACHER", "Teacher")],
                default="TEACHER",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="second_name",
            field=models.CharField(default="unknown"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="subjects",
            field=models.ManyToManyField(null=True, to="education.subject"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(),
        ),
    ]
