# Generated by Django 5.0.2 on 2024-03-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
        ("users", "0002_customuser_age_customuser_group_customuser_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="second_name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="subjects",
            field=models.ManyToManyField(to="education.subject"),
        ),
    ]
