# Generated by Django 5.0.2 on 2024-03-02 16:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(3000)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Semester 1"), (2, "Semester 2")]
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "year",
                    models.PositiveIntegerField(
                        verbose_name=[django.core.validators.MaxValueValidator(3000)]
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="education.discipline",
                    ),
                ),
            ],
        ),
    ]
