# Generated by Django 5.0.2 on 2024-03-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="discipline",
        ),
        migrations.DeleteModel(
            name="Discipline",
        ),
    ]
